apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddoddo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddoddo-db
  template:
    metadata:
      labels:
        app: ddoddo-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "ddoddo"
            - name: POSTGRES_USER
              value: "ddoddo"
            - name: POSTGRES_PASSWORD
              value: "ddoddopw" # <-- ðŸš¨ ë¯¼ê° ì •ë³´!